name: nuget_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/kakao.png
    - assets/naver.png
    - assets/entp.jpg
    - assets/estj.jpg
    - assets/estj2.jpg
    - assets/infp.jpg
    - assets/intj.jpg
    - assets/isfj.jpg
    - assets/avatar.png